name: Run Node.js Script and Create PR

on:
  push:
    branches:
      - main
  # schedule:
    # - cron: 0 23 * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  run_script_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.8.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Install Chrome browser
        run: pnpm --filter @bloger/scrapper chrome-install

           # .env 생성
      - name: create dotenv
        run: |
          touch ./services/uploader/.env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> ./services/uploader/.env
          echo "TISTORY_ACCESS_TOKEN=${{ secrets.TISTORY_ACCESS_TOKEN }}" >> ./services/uploader/.env
          
      - uses: actions/cache@v3
        with:
          path: packages/scrapper/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/packages/scrapper/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ hashFiles('**/packages/scrapper/package-lock.json') }}

      - name: Run Node.js script and get result filename
        id: run_script
        run: |
          # Generate a date-based filename (e.g., 20230928)
          # 요기서 9시간을 더해줘야 한국시간이 나온다.
          current_date="$(TZ=Asia/Seoul date +'%Y%m%d')"

          # Pass the variables as an output
          echo "current_date=$current_date" >> $GITHUB_OUTPUT

          pnpm --filter @bloger/uploader upload "$current_date"
        shell: bash

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ steps.run_script.outputs.current_date }} 경제스크랩 파일 업로드
          title: ${{ steps.run_script.outputs.current_date }} 뉴스 스크랩
          body: 뉴스 스크랩 결과 파일을 업로드합니다.
          branch: ${{ steps.run_script.outputs.current_date }}-economy-scrap
          branch-suffix: timestamp
          base: main
          signoff: false
          delete-branch: true
