name: Run Node.js Script and Create PR

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: 0 23 * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  run_script_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
  
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Chrome browser
        run: |
          cd packages/scrapper
          pnpm chrome-install

      - uses: actions/cache@v3
        with:
          path: packages/scrapper/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/packages/scrapper/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Run Node.js script and get result filename
        id: run_script
        run: |
          # Navigate to the 'services/uploader' directory
          cd services/uploader

          # Generate a date-based filename (e.g., 2023-09-28-경제스크랩)
          current_date="$(date +\%Y-\%m-\%d)"

          # Pass the variables as an output
          echo "current_date=$current_date" >> $GITHUB_ENV

          pnpm upload "$current_date" # Pass the filename as an argument
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.run_script.outputs.current_date }} 경제스크랩 JSON 파일 업로드
          path: content/${{ steps.run_script.outputs.current_date }}/경제스크랩.json

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ steps.run_script.outputs.current_date }} 경제스크랩 JSON 파일 업로드
          title: ${{ steps.run_script.outputs.current_date }} 뉴스 스크랩
          body: 뉴스 스크랩 결과 파일을 업로드합니다.
          branch: ${{ steps.run_script.outputs.current_date }}-경제스크랩
          branch-suffix: timestamp
          base: main
          signoff: false
          delete-branch: true
